# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The numerical solution to HJB-PDE problem for optimal log-utility
#' 
#' @param bankroll the initial bankroll to invest with
#' @param time_length the time-horizon of the investment
#' @param mu the mean rate of return of the stock
#' @param rate the risk-free rate of the money-market account
#' @param volat the annual volatility of the stock
#' @param space_epsilon the truncation towards zero of the space (wealth) variable
#' @param time_res the time resolution for the time-grid
#' @param space_res the space resolution for the space-grid
#' 
#' @description {Numerically solve to the Hamilton-Jacobi-Bellman PDE for the maximal log utility value of a portfolio on a
#' geometric Brownian motion and risk-free money-market account.}
#' @return matrix
explicit_integrator_grid <- function(bankroll, time_length, mu, rate, volat, space_epsilon = 0.001, time_res = 1000L, space_res = 400L) {
    .Call('_LogUtility_explicit_integrator_grid', PACKAGE = 'LogUtility', bankroll, time_length, mu, rate, volat, space_epsilon, time_res, space_res)
}

#' The numerical solution to HJB-PDE problem for optimal log-utility
#' 
#' @param bankroll the initial bankroll to invest with
#' @param time_length the time-horizon of the investment
#' @param mu the mean rate of return of the stock
#' @param rate the risk-free rate of the money-market account
#' @param volat the annual volatility of the stock
#' @param space_epsilon the truncation towards zero of the space (wealth) variable
#' @param time_res the time resolution for the time-grid
#' @param space_res the space resolution for the space-grid
#' 
#' @description {Numerically solve to the Hamilton-Jacobi-Bellman PDE for the maximal log utility value of a portfolio on a
#' geometric Brownian motion and risk-free money-market account.}
#' @return matrix
imex_integrator_grid <- function(bankroll, time_length, mu, rate, volat, space_epsilon = 0.001, time_res = 1000L, space_res = 400L) {
    .Call('_LogUtility_imex_integrator_grid', PACKAGE = 'LogUtility', bankroll, time_length, mu, rate, volat, space_epsilon, time_res, space_res)
}

#' The numerical solution to HJB-PDE problem for optimal log-utility
#' 
#' @param bankroll the initial bankroll to invest with
#' @param time_length the time-horizon of the investment
#' @param mu the mean rate of return of the stock
#' @param rate the risk-free rate of the money-market account
#' @param volat the annual volatility of the stock
#' @param space_epsilon the truncation towards zero of the space (wealth) variable
#' @param time_res the time resolution for the time-grid
#' @param space_res the space resolution for the space-grid
#' 
#' @description {Numerically solve to the Hamilton-Jacobi-Bellman PDE for the maximal log utility value of a portfolio on a
#' geometric Brownian motion and risk-free money-market account.}
#' @return vector
explicit_integrator1 <- function(bankroll, time_length, mu, rate, volat, space_epsilon = 0.001, time_res = 1000L, space_res = 400L) {
    .Call('_LogUtility_explicit_integrator1', PACKAGE = 'LogUtility', bankroll, time_length, mu, rate, volat, space_epsilon, time_res, space_res)
}

#' The numerical solution to HJB-PDE problem for optimal log-utility
#' 
#' @param bankroll the initial bankroll to invest with
#' @param time_length the time-horizon of the investment
#' @param mu the mean rate of return of the stock
#' @param rate the risk-free rate of the money-market account
#' @param volat the annual volatility of the stock
#' @param space_epsilon the truncation towards zero of the space (wealth) variable
#' @param time_res the time resolution for the time-grid
#' @param space_res the space resolution for the space-grid
#' 
#' @description {Numerically solve to the Hamilton-Jacobi-Bellman PDE for the maximal log utility value of a portfolio on a
#' geometric Brownian motion and risk-free money-market account.}
#' @return vector
imex_integrator1 <- function(bankroll, time_length, mu, rate, volat, space_epsilon = 0.001, time_res = 1000L, space_res = 400L) {
    .Call('_LogUtility_imex_integrator1', PACKAGE = 'LogUtility', bankroll, time_length, mu, rate, volat, space_epsilon, time_res, space_res)
}

#' The numerical optimal control value
#' 
#' @param bankroll the initial wealth level
#' @param time_length the time-horizon of the investment
#' @param mu the mean rate of return of the stock
#' @param rate the risk-free rate of the money-market account
#' @param volat the annual volatility of the stock
#' @param space_epsilon the truncation towards zero of the space (wealth) variable
#' @param time_res the time resolution for the time-grid
#' @param space_res the space resolution for the space-grid
#' 
#' @description {Numerically compute the optimal control function/value of the HJB PDE for optimal log utility.}
#' @return matrix
#' @export explicit_control
explicit_control <- function(bankroll, time_length, mu, rate, volat, space_epsilon = 0.001, time_res = 1000L, space_res = 400L) {
    .Call('_LogUtility_explicit_control', PACKAGE = 'LogUtility', bankroll, time_length, mu, rate, volat, space_epsilon, time_res, space_res)
}

#' The numerical optimal control value
#' 
#' @param bankroll the initial wealth level
#' @param time_length the time-horizon of the investment
#' @param mu the mean rate of return of the stock
#' @param rate the risk-free rate of the money-market account
#' @param volat the annual volatility of the stock
#' @param space_epsilon the truncation towards zero of the space (wealth) variable
#' @param time_res the time resolution for the time-grid
#' @param space_res the space resolution for the space-grid
#' 
#' @description {Numerically compute the optimal control function/value of the HJB PDE for optimal log utility.}
#' @return matrix
#' @export imex_control
imex_control <- function(bankroll, time_length, mu, rate, volat, space_epsilon = 0.001, time_res = 1000L, space_res = 400L) {
    .Call('_LogUtility_imex_control', PACKAGE = 'LogUtility', bankroll, time_length, mu, rate, volat, space_epsilon, time_res, space_res)
}

